# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the it6610
#

obj-$(CONFIG_IT6610_HDMI)	+= gpio_i2c.o
obj-$(CONFIG_IT6610_HDMI)	+= chip_sys.o
obj-$(CONFIG_IT6610_HDMI)	+= chip_drv.o
obj-$(CONFIG_IT6610_HDMI)	+= it6610_drv.o
